project:
  type: book
  
description: "An introductory e‑book on Statistics for Business and Economics with practical examples, exercises, and visualizations."
keyword: ["Statistics", "Business", "Economics", "Probability", "Data Analysis","Hypothesis test"]
number-sections: true

book:
  title: "Statistics for Business and Economics"
  author: 
  - name: "Mohammad Saifuddin"
    affiliation: "Assistant Professor, Department of Mathematics and  Statistics, BUBT"

  
  date: today
  cover-image: "cover3.jpg"
  
  
  chapters:
    - index.qmd
    - 1intro.qmd
    - 2descriptive_graph_tab.qmd
    - 3descriptive_numer_measures.qmd
    - 4Probability.qmd
    - 5randomvariable_and_Discrete_dist.qmd
    #- 6.1discrete_r.v_special.qmd
    - 6continuous_Dist.qmd
    - 7Further_topics_on_rv.qmd
    - 8sampling_and_sampling_distributions.qmd
    - 9estimation.qmd
    - 10hypothesis_test.qmd
    - 11Hypotheis_test(TWO population).qmd
    - 12ANOVA_oneway.qmd
    - 13Chi_squaredTest.qmd
    - 14Correlation.qmd
    #- Multiple_linear.qmd
    - summary.qmd
    - references.qmd

  downloads: [pdf, epub]
  sidebar:
    pinned: true
    tools:
      - icon: save
        menu:
          - text: ""
            url:  "#"
          - text: ""
            url:  "#"
          - text: ""
            url:  "#"
            
  repo-url: https://github.com/msaif525/stat_for_businessNeconomics   
  search: 
    location: sidebar
    type: textbox    

execute: 
  echo: false
  warning: false

bibliography: references.bib


format:
  html:
    grid:
      margin-width: 300px
      body-width: 900px
      sidebar-width: 300px
      gutter-width: 1.5rem
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    include-in-header: footer.tex
    geometry:
      - top=20mm
      - bottom=25mm
      - left=25mm
      - right=25mm
      - heightrounded
    toc: true
    toc-depth: 2
    colorlinks: true
    fontsize: 11pt
    include-before-body: cover.tex
  
css: styles.css
editor: visual